### ISSUE TITLE
Update the gitbooks.io version

### ISSUE THREAD

**Issue by noxer** [tumregels/Network-Programming-with-Go#26]
There is a typo on [this page](https://jannewmarch.gitbooks.io/network-programming-with-go-golang-/content/architecture/networking.html#) that has been fixed since [August 2016](https://github.com/tumregels/Network-Programming-with-Go/commit/1bcea5a906ba3699798837917101bf67fa22adab). You should consider regenerating the gitbooks version.

**Comment by tumregels** [comment]
its fixed by now
