### ISSUE TITLE
All print examples have extra spaces

### ISSUE THREAD

**Issue by hackeryarn** [tumregels/Network-Programming-with-Go#28]
So far going through the book, when ever not formatted print is used there is an extra space between the string and concatenation.

E.g. in the below example, the space after the `is` is not needed as `fmt.Println` will add one automatically.
```
 fmt.Println("The address is ", addr.String())
```

I would be happy to go through and correct these as I am reading, unless this was intentional.

**Comment by tumregels** [comment]
Yes, you are right. Just send me a pull request if you can - will merge it

**Comment by shadowz10** [comment]
@tumregels Hello, I would like to translate to Spanish but I do not know how. I would like to do it by means of pull request :)

**Comment by shadowz10** [comment]
@tumregels if I could do it in crowdin

**Comment by tumregels** [comment]
ok @shadowz10 
Here is another suggestion.

Fork the project, check out into branch named sp, translate it and then send me a pull request.
I will merge it into the project as a separate branch.
Later on, I will restructure the code and merge it into one as it is the case for djangogirls.

**Comment by shadowz10** [comment]
@tumregels this project is a open source?

**Comment by tumregels** [comment]
yes, check the license
